{% set name = "libobjcryst" %}
{% set version = "2024.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/diffpy/libobjcryst.git
  git_rev: v2024.2.1
  git_depth: 20
# We need the objcryst submodule, so prefer using a git source
#  fn: {{ name }}-{{ version }}.tar.gz
#  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
#  sha256: 3878a127cd939a1025e95a90713b59d85213eeb5cc6882a493d4670b0e81bc48

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libobjcryst', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - scons
  host:
    - libboost-headers

test:
  commands:
    - test -f $PREFIX/lib/libObjCryst${SHLIB_EXT}                                 # [not win]
    - test -f $PREFIX/include/ObjCryst/version.h                                  # [not win]
    - test -f $PREFIX/include/ObjCryst/CrystVector/CrystVector.h                  # [not win]
    - test -f $PREFIX/include/ObjCryst/ObjCryst/Crystal.h                         # [not win]
    - test -f $PREFIX/include/ObjCryst/Quirks/VFNDebug.h                          # [not win]
    - test -f $PREFIX/include/ObjCryst/RefinableObj/RefinableObj.h                # [not win]
    - if not exist %LIBRARY_LIB%\\libObjCryst.lib exit 1                          # [win]
    - if not exist %LIBRARY_INC%\\ObjCryst\\version.h exit 1                      # [win]
    - if not exist %LIBRARY_INC%\\ObjCryst\\CrystVector\\CrystVector.h exit 1     # [win]
    - if not exist %LIBRARY_INC%\\ObjCryst\\ObjCryst\\Crystal.h exit 1            # [win]
    - if not exist %LIBRARY_INC%\\ObjCryst\\Quirks\\VFNDebug.h exit 1             # [win]
    - if not exist %LIBRARY_INC%\\ObjCryst\\RefinableObj\\RefinableObj.h exit 1   # [win]

about:
  home: https://github.com/diffpy/libobjcryst/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: ObjCryst++ packaged for installation as a shared library.

  description: |
    ObjCryst++ is Object-Oriented Crystallographic Library for C++ developed
    by Vincent Favre-Nicolin. libobjcryst is a mirror of the ObjCryst++
    sources from https://sourceforge.net/projects/objcryst, expanded with
    SCons build scripts to make it easier to install as a system shared
    library. libobjcryst does not include GUI related files from ObjCryst++.
    This distribution contains required sources from cctbx and newmat that are
    used in ObjCryst++.
  doc_url: https://github.com/diffpy/libobjcryst
  dev_url: https://github.com/diffpy/libobjcryst

extra:
  recipe-maintainers:
    - vincefn
    - pavoljuhas
    - sbillinge
    - st3107
