{% set name = "libobjcryst" %}
{% set version = "2017.2.3" %}
{% set sha256 = "d48de43a15c3227ac39422831c31285c695f8ec560b31420f0f31356de1a3bb0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libobjcryst', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - scons
  host:
    - libboost

test:
  commands:
    - test -f $PREFIX/lib/libObjCryst${SHLIB_EXT}

about:
  home: https://github.com/diffpy/libobjcryst/
  license: GPL2
  license_family: GPL
  license_file: LICENSE.txt
  summary: ObjCryst++ packaged for installation as a shared library.

  description: |
    ObjCryst++ is Object-Oriented Crystallographic Library for C++ developed
    by Vincent Favre-Nicolin. libobjcryst is a mirror of the ObjCryst++
    sources from https://sourceforge.net/projects/objcryst, expanded with
    SCons build scripts to make it easier to install as a system shared
    library. libobjcryst does not include GUI related files from ObjCryst++.
    This distribution contains required sources from cctbx and newmat that are
    used in ObjCryst++.
  doc_url: https://github.com/diffpy/libobjcryst
  dev_url: https://github.com/diffpy/libobjcryst

extra:
  recipe-maintainers:
    - pavoljuhas
