# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython2.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kD6YMKeKzIYbGmqpVOz7ku0hi4n3tQAvGKYWPprje/F7gU23FvoLmpros1adVF7IOBIWsv41oEu4v6dNCVggeGqaxPjEqLmqZ0mW5rplw0lZGB1PkUJvw0KBj6cT4V1h1ysMldSYKFFIT8K/RH3kjnBBYjTmi88oiYpVKZGCbWfvsLbqsMUmc5nPEyte6XT6LjJgetEquWsUJtq2MRbyBmDm1gTQjyBUvM/MGCGIB9zh0Af9w/Okop3aIS7t82KTPC8r4vQm+KSYtzlmkOvJIi2SYjI4ga+BzUYjOvO4GwCsD+TLe7bUX4oBPXVFRMuWUuRe9UAKmMoB5fMvs95R23vqp0lpHclbFp/MUfciXflkCEVwUrYRI5LHSsR6p1jQeXE79NCRwjH+C98Ckh3DUXfolzbbHie7VZLlkYSZ0CKxheBLx4bt6pl45YAlV/kong5UMtKtGHlpDjjA0V8MiOGOclmBvuAwpOdp75qyNQgaVV7q6WvoPgF9G84IjXPIKSjqDXhgPADaaZBrMEdqI0Xl5tZu/ZXNQgN4LNu2dXLdJgy84ZgpVP9m1bCQJmOf+9r6Dm57sK7qAcnjJsAOFbVPjHFWRCBQMR8cjiclGaYwyk8uOqejt0kX8W6D6aHe+u6CguryjmZthNqsKqp9/O36dgSE+E9HxR1XfZ36+4U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
