travis:
  secure:
    BINSTAR_TOKEN: kD6YMKeKzIYbGmqpVOz7ku0hi4n3tQAvGKYWPprje/F7gU23FvoLmpros1adVF7IOBIWsv41oEu4v6dNCVggeGqaxPjEqLmqZ0mW5rplw0lZGB1PkUJvw0KBj6cT4V1h1ysMldSYKFFIT8K/RH3kjnBBYjTmi88oiYpVKZGCbWfvsLbqsMUmc5nPEyte6XT6LjJgetEquWsUJtq2MRbyBmDm1gTQjyBUvM/MGCGIB9zh0Af9w/Okop3aIS7t82KTPC8r4vQm+KSYtzlmkOvJIi2SYjI4ga+BzUYjOvO4GwCsD+TLe7bUX4oBPXVFRMuWUuRe9UAKmMoB5fMvs95R23vqp0lpHclbFp/MUfciXflkCEVwUrYRI5LHSsR6p1jQeXE79NCRwjH+C98Ckh3DUXfolzbbHie7VZLlkYSZ0CKxheBLx4bt6pl45YAlV/kong5UMtKtGHlpDjjA0V8MiOGOclmBvuAwpOdp75qyNQgaVV7q6WvoPgF9G84IjXPIKSjqDXhgPADaaZBrMEdqI0Xl5tZu/ZXNQgN4LNu2dXLdJgy84ZgpVP9m1bCQJmOf+9r6Dm57sK7qAcnjJsAOFbVPjHFWRCBQMR8cjiclGaYwyk8uOqejt0kX8W6D6aHe+u6CguryjmZthNqsKqp9/O36dgSE+E9HxR1XfZ36+4U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
